### ISSUE TITLE
ui_widgetchat.h: fatal error: chatlineedit.h: No such file or directory

### ISSUE THREAD

**Issue by barracuda156** [tjohnman/Obsession#44]
@tjohnman Something has broken since November 6, apparently:
```
:info:build In file included from src/widgetchat.cpp:2:
:info:build ./ui_widgetchat.h:24:10: fatal error: chatlineedit.h: No such file or directory
:info:build    24 | #include "chatlineedit.h"
:info:build       |          ^~~~~~~~~~~~~~~~
:info:build compilation terminated.
:info:build make: *** [widgetchat.o] Error 1
```

**Comment by barracuda156** [comment]
The build from 6cc3951ccc69a772f5944ac16ab1e3e92e7efb7c commit is perfectly fine at the same time (i.e. I have rebuilt it now to verify it is not environment that got broken).

**Comment by tjohnman** [comment]
Sorry about that. I messed up the include path when I organized the directory structure. It should be fixed now.

**Comment by barracuda156** [comment]
@tjohnman Thank you. I will try today.

UPD. Yes, all good now.
