### ISSUE TITLE
ICONS upside down

### ISSUE THREAD

**Issue by vido420** [tjohnman/Obsession#46]
<img width="842" alt="Screenshot 2024-04-27 at 11 49 57 PM" src="https://github.com/tjohnman/Obsession/assets/6705846/9b8c2df2-ea4e-45d0-8bc3-a54a6b6102d8">

Noticed that the ICONS are now upside down. Like the client. Keep working lets boost it up.

**Comment by tjohnman** [comment]
This is an interesting bug. Maybe this has to do with a particular server implementation. Can you give me more information please? Does this happen with every server?

**Comment by tjohnman** [comment]
I just tested this on a couple of servers and I could see the icons just fine. I will need more information on how to reproduce this.

**Comment by tjohnman** [comment]
Closing for now until we can reproduce it.
