### ISSUE TITLE
Bookmarking from the new connection dialog is erratic

### ISSUE THREAD

**Issue by tjohnman** [tjohnman/Obsession#47]

**Comment by zquestz** [comment]
Can you elaborate? It seems to be working fine for me. =)

**Comment by tjohnman** [comment]
I did not write a description because I wrote it for myself, but if you want to check it out, basically the problem is that when you save a bookmark from the new connection dialog, sometimes it gets saved with data from the previously selected one, or when selecting it back, something or other breaks... That kind of thing. It's really inconsistent. It probably needs a rewrite.

**Comment by zquestz** [comment]
Gotcha, was just curious. Was trying to see if I could tackle any of the issues here. =)
