### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by tagban** [tjohnman/Obsession#52]
Heya as a former Digital Obsession member myself (LostArch). I was so excited to see you bringing this back! I'd love to see it default to hltracker.com for n00bs to be able to find their way into a server relatively fast. hlserver.com and hltracker.com are both maintained by Ari as we captured the official domains from old squatters and are ensuring they stay with the community moving forward.

No worries if you don't want to. The old DO server might be gone, but stickytack is still around. And as you probably saw we've been seeing a massive increase in servers thanks to Mobius and more people from the classic mac community. I'd recommend you consider elevating to more modern QT to support more modern OS's as we have tons of old clients to pick from but more modern systems have like 4. (And lets face it Pitbull is NOT a great client for Windows... this thing works smooth as butter compared to it)

Anyway I hangout on "Mac on Hotline" server, which is synced to a Discord server for Macintosh Garden. :)

**Comment by zquestz** [comment]
I wrote a patch-set for Qt5, but it seems this project is staying on Qt4.

That being said, the patch is powering the AUR version for Arch Linux users.

https://aur.archlinux.org/cgit/aur.git/tree/qt5.patch?h=obsession-git

**Comment by tagban** [comment]
I suspect you'd be better off making a QT5 Branch so that it could be continued on for that I personally would like to re-write some server code to be more modern to support Encryption (Similar to pitbull), and to handle other things. Obsession is one of the better clients available and works in places Pitbull and other mac clients don't so i genuinely love it.

**Comment by zquestz** [comment]
The qt5 branch exists in my fork. I have been talking to the mobius server dev a bunch, and we have a decent plan to implement TLS connections. I think a modern Hotline might actually surface again!

https://github.com/zquestz/Obsession/tree/qt5

**Comment by tagban** [comment]
Thats cool, and forking things is awesome, but @tjohnman might actually let you just take over a branch here to ensure all of the development stays super close. I love the idea of this continuing. I was around when Obsession first came out in alpha testing. :)

**Comment by tjohnman** [comment]
> I suspect you'd be better off making a QT5 Branch so that it could be continued on for that I personally would like to re-write some server code to be more modern to support Encryption (Similar to pitbull), and to handle other things. Obsession is one of the better clients available and works in places Pitbull and other mac clients don't so i genuinely love it.

Thank you for those kinds words!

@zquestz are you planning on documenting those plans somewhere? It sounds interesting.

**Comment by tagban** [comment]
@tjohnman  Sure thing man. I miss seeing you in the DO server. Do you hangout anywhere else? I'm constantly on the Mac on Hotline (MacintoshGarden+System7Today Hotline/Discord)

**Comment by tjohnman** [comment]
> @tjohnman Sure thing man. I miss seeing you in the DO server. Do you hangout anywhere else? I'm constantly on the Mac on Hotline (MacintoshGarden+System7Today Hotline/Discord)

Not really. Back then I had a lot of free time, and as you know I spent a lot of time on DO. But nowadays it's just a few minutes here and there. But I do try to check what's going on whenever I can.

By the way, I just pushed a commit with the changes you suggested: [3a7fd98](https://github.com/tjohnman/Obsession/commit/3a7fd98d8c417ad6942f7add64460e3df8811d0f).

**Comment by tjohnman** [comment]
By the way, the whole Qt 4 thing is a bit awkward because I actually downgraded it so that it would work on older macs. Qt 4 is still perfectly functional on both Windows and Linux as well, so I don't think it's a problem to keep it. Hotline being venerable software as it is, I think it makes sense to try to maintain as broad backwards compatibility as possible. As far as I know, it shouldn't be a problem when it comes to implementing SSL or anything else, as most improvements in Qt we are likely to miss are OS integration stuff.

**Comment by zquestz** [comment]
Only issue is for high resolution screens. The options to fix Linux UI scaling issues were released in Qt5.

**Comment by tjohnman** [comment]
> Only issue is for high resolution screens. The options to fix Linux UI scaling issues were released in Qt5.

That sucks. But there seem to be some experimental solutions that might work in this case, and I can test them on Linux. I'll try and see. Thanks for letting me know.

**Comment by tjohnman** [comment]
@zquestz I pushed a Qt6 branch. I hope UI scaling works with that version. I will look into dark mode too (soon?), since I remember some people asked for it.
